WIP: join base impl
Wandalen/posixutils-rs pull request #59
Opened 2024-07-25 05:02 UTC by Sakapoi

2024-07-31 06:36 UTC, 0x07C0 requested changes
Please, rework your data structures too, `H<S, V<V<S>>>` can't be optimal. And find a way to minimize cloning, Almost every string gets cloned multiple times.

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +    v: Option<u8>,
Fields for argument names should be descriptive. No need for `long` args here,

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +    field2: usize,
This args don't have long variants in linux util.

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +    for line in reader.lines() {
Reading the whole file will result in out of memory and crush the app. Reading from files needs to be heavily refactored

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +    }
Just set default values for those args, so you don't have to unwrap with default every time.

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +        return Err(format!("field 1 and field 2 must be greater than one").into());
Why do we need `format!` and `.into()` here? Also, f1 and f2 can be equal to 1 too, not greater then.

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +            for num in o.clone().unwrap() {
You shouldn't use is_some followed by unwrap. Use `if let Some()`

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +    let file = File::open(file_path).map_err(|_| format!("Unable to open file"))?;
You have not accounted for stdin as an input.

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +                        res.push(e.clone().unwrap());
is_some followed by unwrap

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +                    res.push(s[f_num[1].parse::<usize>().unwrap() - 1].clone());
Don't unwrap on usize parse

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +    if o.is_some() {
This whole block looks like it could've been a separate function.

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +            let mut output = vec![String::from("(unknown)")];
Empty fields by default stay empty. `-e` is used to replace them with a custom filed.

2024-07-31 06:36 UTC, 0x07C0 commented on file/tests/join/mod.rs
> +}
Both tests represent default behavior.

2024-07-31 06:36 UTC, 0x07C0 commented on file/join.rs
> +                output.extend_from_slice(&line[1..]);
Will this work for cases where the key is not the first column in the file? Also wouldn't doing it in a loop duplicate the data for each match?

2024-08-07 07:00 UTC, SupperZum requested changes

2024-08-07 07:00 UTC, SupperZum commented on file/join.rs
> +    }
file2_cache can lead to memory overflow and crash the app. Correct me if I'm wrong.

2024-08-09 07:04 UTC, SupperZum approved these changes

2024-08-09 08:36 UTC, merged