NOT READY: talk
Wandalen/posixutils-rs pull request #63
Opened 2024-08-16 06:45 UTC by Sakapoi

2024-08-22 11:53 UTC, SupperZum approved these changes

2024-08-26 11:07 UTC, SupperZum requested changes
.

2024-08-30 12:44 UTC, 0x07C0 reviewed
Please review the actual implementation of the `talk` utility: http://deb.debian.org/debian/pool/main/i/inetutils/inetutils_2.5.orig.tar.xz

This implementation doesn't follow the specification at all.

2024-08-30 12:44 UTC, 0x07C0 commented on users/talk.rs
> +    println!("Message from <unspecified string>");
That's not a static text. `<unspecified string>` should instead show who is trying to talk to this tty. Example:
```
Message from TalkDaemon@his_machine...
talk: connection requested by your_name@your_machine.
talk: respond with: talk your_name@your_machine
```
See https://linux.die.net/man/1/talk

2024-08-30 12:44 UTC, 0x07C0 commented on users/tests/talk/mod.rs
> +}
This is an incorrect usage of this utility.

See: https://pubs.opengroup.org/onlinepubs/9799919799/
See: https://linux.die.net/man/1/talk

2024-08-30 12:44 UTC, 0x07C0 commented on users/talk.rs
> +        let listener = TcpListener::bind(&address)?;
Input is not a socket address. Correct input is `username[@machine]`.

2024-08-30 12:44 UTC, 0x07C0 commented on users/talk.rs
> +    let mut stdout = io::stdout().into_raw_mode()?;
Don't leave the terminal in raw mode after exiting.

2025-01-13 15:41 UTC, closed without merging