WIP: `talk`
Wandalen/posixutils-rs pull request #68
Opened 2024-09-05 05:51 UTC by Inkvisto

2024-09-18 13:31 UTC, SupperZum requested changes

2024-09-18 13:31 UTC, SupperZum commented on users/tests/talk/mod.rs
деякі функції повертають io::Error, а інші використовують TalkError. Але так як в TalkError є io::Error краще уніфікувати помилки всі під TalkError.

2024-09-18 13:31 UTC, SupperZum commented on users/talk.rs
Невистачає повної документаціїї до всіх функцій та структур. Розписуй будь ласка що робить функція і які аругменти за що відповідають.

2024-09-18 13:31 UTC, SupperZum commented on users/talk.rs
> +            _ => Err(()),
тут не завадило б описати помилку. Не залишай помилки як пусті, будь ласка.

2024-09-18 13:31 UTC, SupperZum commented on users/talk.rs
> +            _ => Err(()),
Не залишай помилки як пусті, будь ласка.

2024-09-18 13:31 UTC, SupperZum commented on users/talk.rs
> +struct CtlMsg {
можна використати #[derive(Serialize, Deserialize)]
для уникненя зайового коду як в "fn to_bytes"

2024-09-18 13:31 UTC, SupperZum commented on users/talk.rs
> +pub struct CtlRes {
можна використати #[derive(Serialize, Deserialize)]
для уникненя зайового коду як в "fn from_bytes"

2024-09-18 13:31 UTC, SupperZum commented on users/talk.rs
> +    }
мені здається більш ідеоматично буде зробити це через трейт дефолт


```
impl Default for CtlMsg {
    fn default() -> Self {
        CtlMsg {
            vers: 1,
            r#type: MessageType::LookUp as u8,
            answer: Answer::Success as u8,
            pad: 0,
            id_num: 0,
            addr: Osockaddr::default(),
            ctl_addr: Osockaddr::default(),
            pid: 0,
            l_name: string_to_c_string(""),
            r_name: string_to_c_string(""),
            r_tty: [0; 16],
        }
    }
}

```

2024-09-18 13:31 UTC, SupperZum commented on users/talk.rs
> +    }
теж стосується CtlRes

2024-09-18 13:31 UTC, SupperZum commented on users/talk.rs
> +}
Рекомендую повернути помилку у випадку невдачі.


return Err(TalkError::NotTty);

2024-09-18 13:31 UTC, SupperZum commented on users/talk.rs
> +    let write_stream = stream.try_clone()?;
Якщо під час роботи виникає помилка (наприклад, клієнт раптово відключається), необхідно коректно обробити цю ситуацію та завершити обидва потоки.

2024-09-18 15:40 UTC, 0x07C0 requested changes
Please convert regular comments to doc comments where necessary and try using `thiserror` and `binrw`.

I didn't quite understand the need in the `invites.txt` file - seems like a painful hack that will bite when you least expect it.

Overall this is a huge improvement from the implementation we've had before, so great job!

2024-09-18 15:40 UTC, 0x07C0 commented on users/talk.rs
> +}
Why are we writing to a file at all?

Where is this file created?

What if the file exists/created by the user?

2024-09-18 15:40 UTC, 0x07C0 commented on users/talk.rs
> +fn reqwest(
request

2024-09-18 15:40 UTC, 0x07C0 commented on users/talk.rs
> +pub enum TalkError {
Are we allowed to use `thiserror`? It would simplify error handling an propagation by quite a bit

2024-09-18 15:40 UTC, 0x07C0 commented on users/talk.rs
> +fn spawn_read_thread(
How is this different from spawn_input_thread?

2024-09-18 15:40 UTC, 0x07C0 commented on users/talk.rs
> +fn draw_terminal(split_row: u16, width: u16) -> io::Result<io::StdoutLock<'static>> {
Probably best to switch to the raw mode too. I haven't seen you doing it anywhere. I expect there's quite a bit of lag of the input while in cooked mode.

2024-09-18 15:40 UTC, 0x07C0 commented on users/talk.rs
> +fn handle_connection_close() {
If you've changed to the raw mode or will after the previous comment - don't forget to return to normal after.

2024-09-18 18:31 UTC, SupperZum commented on users/tests/talk/mod.rs
Про це я не подумав, дійсно, ти правий.

2024-09-23 08:05 UTC, SupperZum approved these changes

2024-09-26 07:45 UTC, 0x07C0 approved these changes

2024-09-26 10:39 UTC, merged